blueprint:
  name: IKEA STYRBAR (Zigbee2MQTT) – last-target brightness (areas/groups)
  description: >
    Use an IKEA STYRBAR remote via Zigbee2MQTT.

    - "on" toggles Light A target and marks it as last target
    - "off" toggles Light B target and marks it as last target
    - "arrow_left_click" dims either:
        * the last-pressed target (ON/OFF), or
        * always the ON target (depending on mode)
    - "arrow_right_click" brightens similarly

    Light targets can be single entities, groups, devices or areas.
    Requires Zigbee2MQTT action sensor and an input_text helper
    to store "on" / "off" as the last target.
  domain: automation

  input:
    remote_action:
      name: STYRBAR action sensor
      description: The Zigbee2MQTT action sensor (e.g. sensor.styrbar_action)
      selector:
        entity:
          domain: sensor

    light_on_target:
      name: Target for ON button (Light A)
      description: >
        Target to toggle when ON is pressed (entity, group, device or area).
      selector:
        target:
          entity:
            domain: light

    light_off_target:
      name: Target for OFF button (Light B)
      description: >
        Target to toggle when OFF is pressed (entity, group, device or area).
      selector:
        target:
          entity:
            domain: light

    last_target_helper:
      name: Last target text helper
      description: >
        input_text entity used to remember which target was last used.
        This will store "on" or "off".
      selector:
        entity:
          domain: input_text

    brightness_mode:
      name: Brightness mode
      description: >
        - last_pressed: arrows control whichever (ON/OFF) was pressed last
        - on_only: arrows always control the ON target
      default: last_pressed
      selector:
        select:
          options:
            - last_pressed
            - on_only

    brightness_step:
      name: Brightness step (%)
      description: >
        How much to change brightness per arrow click.
        Left arrow = -step, Right arrow = +step.
      default: 20
      selector:
        number:
          min: 1
          max: 100
          mode: slider
          unit_of_measurement: "%"

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input remote_action

variables:
  action: "{{ trigger.to_state.state }}"
  last_helper: !input last_target_helper
  brightness_mode: !input brightness_mode
  brightness_step: !input brightness_step

action:
  - choose:
      # ─── ON button: toggle ON target and mark "on" ───
      - conditions:
          - condition: template
            value_template: "{{ action == 'on' }}"
        sequence:
          - service: light.toggle
            target: !input light_on_target
          - service: input_text.set_value
            target:
              entity_id: "{{ last_helper }}"
            data:
              value: "on"

      # ─── OFF button: toggle OFF target and mark "off" ───
      - conditions:
          - condition: template
            value_template: "{{ action == 'off' }}"
        sequence:
          - service: light.toggle
            target: !input light_off_target
          - service: input_text.set_value
            target:
              entity_id: "{{ last_helper }}"
            data:
              value: "off"

      # ─── LEFT arrow: dim last-target (or ON-only) ───
      - conditions:
          - condition: template
            value_template: "{{ action == 'arrow_left_click' }}"
        sequence:
          - choose:
              # If mode is last_pressed and last was OFF → dim OFF target
              - conditions:
                  - condition: template
                    value_template: >
                      {{ brightness_mode == 'last_pressed'
                         and states(last_helper) == 'off' }}
                sequence:
                  - service: light.turn_on
                    target: !input light_off_target
                    data:
                      brightness_step_pct: "{{ (brightness_step | int) * -1 }}"
            default:
              # Otherwise (ON-only mode, or last not OFF) → dim ON target
              - service: light.turn_on
                target: !input light_on_target
                data:
                  brightness_step_pct: "{{ (brightness_step | int) * -1 }}"

      # ─── RIGHT arrow: brighten last-target (or ON-only) ───
      - conditions:
          - condition: template
            value_template: "{{ action == 'arrow_right_click' }}"
        sequence:
          - choose:
              # If mode is last_pressed and last was OFF → brighten OFF target
              - conditions:
                  - condition: template
                    value_template: >
                      {{ brightness_mode == 'last_pressed'
                         and states(last_helper) == 'off' }}
                sequence:
                  - service: light.turn_on
                    target: !input light_off_target
                    data:
                      brightness_step_pct: "{{ brightness_step | int }}"
            default:
              # Otherwise (ON-only mode, or last not OFF) → brighten ON target
              - service: light.turn_on
                target: !input light_on_target
                data:
                  brightness_step_pct: "{{ brightness_step | int }}"

  - default: []
