blueprint:
  name: Styrbar remote
  description: >
    IKEA STYRBAR over Zigbee2MQTT.

    - "on"  toggles the ON target (lights and/or switches)
    - "off" toggles the OFF target (lights and/or switches)
    - "arrow_left_click"  dims the brightness target
    - "arrow_right_click" brightens the brightness target

    ON/OFF targets can be entities, groups, devices or areas containing
    lights and/or switches. Brightness target is lights only; if empty,
    the arrow buttons do nothing.
  domain: automation
  source_url: https://raw.githubusercontent.com/Daiki0613/HomeAssistant/main/styrbar.yaml

  input:
    remote_action:
      name: STYRBAR action sensor
      description: The Zigbee2MQTT action sensor (e.g. sensor.styrbar_action)
      selector:
        entity:
          domain: sensor

    on_target:
      name: Target for ON button
      description: >
        Target to toggle when ON is pressed (entity, group, device or area)
        containing lights and/or switches.
      selector:
        target:
          entity:
            domain:
              - light
              - switch

    off_target:
      name: Target for OFF button
      description: >
        Target to toggle when OFF is pressed (entity, group, device or area)
        containing lights and/or switches.
      selector:
        target:
          entity:
            domain:
              - light
              - switch

    brightness_target:
      name: Brightness target (optional)
      description: >
        Light target whose brightness will be changed by the arrow buttons.
        If left empty, arrow buttons do nothing.
      default: {}
      selector:
        target:
          entity:
            domain: light

    brightness_step:
      name: Brightness step (%)
      description: >
        How much to change brightness per arrow click.
        Left arrow = -step, Right arrow = +step.
      default: 20
      selector:
        number:
          min: 1
          max: 100
          mode: slider
          unit_of_measurement: "%"

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input remote_action

variables:
  # Zigbee2MQTT sometimes uses the state, sometimes an "action" attribute.
  action: >-
    {% if 'action' in trigger.to_state.attributes %}
      {{ trigger.to_state.attributes.action }}
    {% else %}
      {{ trigger.to_state.state }}
    {% endif %}
  brightness_step: !input brightness_step
  brightness_target: !input brightness_target
  has_brightness_target: "{{ brightness_target | length > 0 }}"

action:
  - choose:
      # ─── ON button: toggle ON target ───
      - conditions:
          - condition: template
            value_template: "{{ action == 'on' }}"
        sequence:
          - service: homeassistant.toggle
            target: !input on_target

      # ─── OFF button: toggle OFF target ───
      - conditions:
          - condition: template
            value_template: "{{ action == 'off' }}"
        sequence:
          - service: homeassistant.toggle
            target: !input off_target

      # ─── LEFT arrow: dim brightness target ───
      - conditions:
          - condition: template
            value_template: "{{ action == 'arrow_left_click' }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ has_brightness_target }}"
            then:
              - service: light.turn_on
                target: !input brightness_target
                data:
                  brightness_step_pct: "{{ (brightness_step | int) * -1 }}"

      # ─── RIGHT arrow: brighten brightness target ───
      - conditions:
          - condition: template
            value_template: "{{ action == 'arrow_right_click' }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ has_brightness_target }}"
            then:
              - service: light.turn_on
                target: !input brightness_target
                data:
                  brightness_step_pct: "{{ brightness_step | int }}"
    default: []
